added episode/season to rss feed

diff --git a/lbp b/lbp
--- a/lbp
+++ b/lbp
@@ -9,7 +9,7 @@ rssfile="rss.xml"
 archivefile="$webdir/blog/.htaccess"
 #podfile="$webdir/blog/.podfile"
 audiodir="audio"
-torrentdir="torrent"
+#torrentdir="torrent"
 coverdir="img/coverart"
 smallcoverdir="img/smallcoverart"
 [ -z "$EDITOR" ] && EDITOR="vim"
@@ -23,7 +23,7 @@ read -erp "Initialize blog in $webdir?" ask &&
 
 	mkdir -pv "$webdir/$audiodir" || printf "Error. Do you have write permissions in this directory?\\n"
 
-	mkdir -pv "$webdir/$torrentdir" || printf "Error. Do you have write permissions in this directory?\\n"
+	#mkdir -pv "$webdir/$torrentdir" || printf "Error. Do you have write permissions in this directory?\\n"
 
 	mkdir -pv "$webdir/$coverdir" || printf "Error. Do you have write permissions in this directory?\\n"
 
@@ -50,9 +50,9 @@ newpost() { read -erp "Give a title for your post/episode:
 	" audiofile
 	echo "$audiofile" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in audo files.\\n" && exit
 
-	read -erp "Enter the name of your .torrent file: (e.g My-Podcast.torrent):
-	" torrentfile
-	echo "$torrentfile" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in torrent files.\\n" && exit
+	#read -erp "Enter the name of your .torrent file: (e.g My-Podcast.torrent):
+	#" torrentfile
+	#echo "$torrentfile" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in torrent files.\\n" && exit
 
 	read -erp "Give the episode a short description:
 	" shortdesc
@@ -73,10 +73,10 @@ newpost() { read -erp "Give a title for your post/episode:
 
 	url="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
 
-	echo "AddDescription \"$title\" \"$torrentfile\" \"$shortdesc\" \"$audiofile\" \"$duration\" \"$cover\" \"$episode\" \"$season\" \"$url.html\" " >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
+	echo "AddDescription \"$title\" \"$shortdesc\" \"$audiofile\" \"$duration\" \"$cover\" \"$episode\" \"$season\" \"$url.html\" " >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
 	( [ -f "$webdir/blog/.drafts/$url.html" ] || [ -f "$webdir/blog/$url.html" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
 
-	printf "<div class='content'>\\n<img src='%s%s/%s'>\\n<p>%s</p>\\n</div>\\n<div class='Links'>\\n<a href='%s%s/%s'>Ljudfil</a>\\n<a href='%s%s/%s'>Torrent</a>\\n</div>" "$website" "$smallcoverdir" "$cover" "$shortdesc" "$website" "$audiodir" "$audiofile" "$website" "$torrentdir" "$torrentfile" > "$webdir/blog/.drafts/$url.html"
+	printf "<div class='content'>\\n<img src='%s%s/%s'>\\n<p>%s</p>\\n</div>\\n<div class='Links'>\\n<a href='%s%s/%s'>Ljudfil</a>\\n</div>" "$website" "$smallcoverdir" "$cover" "$shortdesc" "$website" "$audiodir" "$audiofile" > "$webdir/blog/.drafts/$url.html"
 
 	$EDITOR "$webdir/blog/.drafts/$url.html" ;
 }
@@ -97,7 +97,7 @@ publish() { \
 	delete draft
 	htaccessentry=$(grep "$basefile" "$archivefile")
 	realname="$(echo "$htaccessentry" | cut -d'"' -f2)"
-	torrentfile="$(echo "$htaccessentry" | cut -d'"' -f4)"
+	#torrentfile="$(echo "$htaccessentry" | cut -d'"' -f4)"
 	shortdesc="$(echo "$htaccessentry" | cut -d'"' -f6)"
 	audiofile="$(echo "$htaccessentry" | cut -d'"' -f8)"
 	duration="$(echo "$htaccessentry" | cut -d'"' -f10)"
@@ -110,14 +110,14 @@ publish() { \
 	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
 	tmpdir=$(mktemp -d)
 	printf "<!DOCTYPE html>\\n<html lang=\"en\">\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>link</a>&mdash;<a href='%s'>standalone</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$css" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
-printf "\\n<item>\\n<title>%s</title>\\n<guid isPermaLink=\"true\">%s%s/%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n<p>%s</p>\\n]]></description>\\n<content:encoded><![CDATA[\\n%s\\n]]></content:encoded>\\n<enclosure length=\"%s\" type=\"audio/mpeg\" url=\"%s%s/%s\" />\\n<itunes:episodeType>full</itunes:episodeType>\\n<itunes:duration>%s</itunes:duration>\\n<link>%s%s#%s%s</link>\\n<itunes:image href=\"%s%s/%s\"/>\\n</item>\\n\\n" "$realname" "$website" "$audiodir" "$audiofile" "$rssdate" "$shortdesc" "$(cat "$webdir/blog/.drafts/$basefile")" "$enclosure_length" "$website" "$audiodir" "$audiofile" "$duration" "$website" "Html/Avsnitt.html" "$episode" "$season" "$website" "$coverdir" "$cover" >  "$tmpdir/rss"
+printf "\\n<item>\\n<title>%s</title>\\n<guid isPermaLink=\"true\">%s%s/%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n<p>%s</p>\\n]]></description>\\n<content:encoded><![CDATA[\\n%s\\n]]></content:encoded>\\n<enclosure length=\"%s\" type=\"audio/mpeg\" url=\"%s%s/%s\" />\\n<itunes:episodeType>full</itunes:episodeType>\\n<itunes:duration>%s</itunes:duration>\\n<itunes:episode>%s</itunes:episode>\\n<itunes:season>%s</itunes:season>\\n<link>%s%s#%s%s</link>\\n<itunes:image href=\"%s%s/%s\"/>\\n</item>\\n\\n" "$realname" "$website" "$audiodir" "$audiofile" "$rssdate" "$shortdesc" "$(cat "$webdir/blog/.drafts/$basefile")" "$enclosure_length" "$website" "$audiodir" "$audiofile" "$duration"  "$episode" "$season" "$website" "Html/Avsnitt.html" "$episode" "$season" "$website" "$coverdir" "$cover" >  "$tmpdir/rss"
 	printf "<article class='Avsnitt'>\\n<h2 id='%s%s'>%s</h2>\\n<small>Avsnitt %s, Säsong %s - %s</small>\\n%s\\n</article>\\n" "$episode" "$season" "$realname" "$episode" "$season" "$webdate" "$(cat "$webdir/blog/.drafts/$basefile")" > "$tmpdir/html"
 	printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/index"
 	sed -i "/<!-- LBP -->/r $tmpdir/html" "$blogfile"
 	sed -i "/<!-- LBP -->/r $tmpdir/rss" "$rssfile"
 	sed -i "/<!-- LBP -->/r $tmpdir/index" "$indexfile"
 		sed -i "/ \"$base.html\"/d" "$archivefile" #deletes old archivefile entry
-		echo "AddDescription \"$realname\" \"$torrentfile\" \"$shortdesc\" \"$audiofile\" \"$duration\" \"$cover\" \"$episode\" \"$season\" \"$basefile\" #$rssdate" >> "$archivefile" #adds new archivefile entry, with datea
+		echo "AddDescription \"$realname\" \"$shortdesc\" \"$audiofile\" \"$duration\" \"$cover\" \"$episode\" \"$season\" \"$basefile\" #$rssdate" >> "$archivefile" #adds new archivefile entry, with datea
 		rm -f "$webdir/blog/.drafts/$chosen"
 	}
 
